/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ghost;
import processing.core.PApplet;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test 
    public void AppConstructorTest() {
        //testing app can be initialised.
        App app = new App();
        assertNotNull(app);
    }
}
